version: "3.3"
services:
  db:
    image: postgres:13.3
    #restart: always
    environment:
      POSTGRES_USER: owner
      POSTGRES_PASSWORD: password
      POSTGRES_DB: core
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data

